It executes (does not mean PASSES WITH OK) all the tests execpt "diacritics_and_ligatures" and "tolerance"

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -1,6 +1,7 @@
 PREFIX=test
 SUFFIX=moodle
-DONOTTEST_THOSE_FILES=test_calculated_python.tex test_generalfeedback.tex test_includegraphics_via_tikz.tex test_minted.tex test_diacritics_and_ligatures.tex test_german.tex test_includegraphics_via_tikz_and_svg.tex test_punctuation_and_symbols.tex test_turkish.tex test_french.tex test_includegraphics.tex test_includegraphics_with_svg.tex test_tikz_with_svg.tex test_tolerance.tex
+BRANCH_SPECIFIC_EXCLUDED_FILES=
+DONOTTEST_THOSE_FILES=$(BRANCH_SPECIFIC_EXCLUDED_FILES) test_diacritics_and_ligatures.tex test_tolerance.tex
 PDFLATEX_EXCLUDED_TEST_FILES=$(DONOTTEST_THOSE_FILES) test_calculated_lua.tex
 XETEX_EXCLUDED_TEST_FILES=$(DONOTTEST_THOSE_FILES) test_calculated_lua.tex
 LUATEX_EXCLUDED_TEST_FILES=$(DONOTTEST_THOSE_FILES) test_calculated_lua.tex test_tags.tex
@@ -11,7 +12,7 @@ LUATEX_TEST_FILES = $(filter-out $(LUATEX_EXCLUDED_TEST_FILES),$(ALL_TEST_FILES)
 TEX_ENGINES=pdflatex xelatex lualatex
 LATEXFLAGS=-halt-on-error -shell-escape
 DIFFTOOL=diff -abBwZ
-FILE_CLEAN=*.diff *.log *.aux *.auxlock *.out *.blg *.bbl *.toc *.xml *.bcf *.synctex.gz *~ *.nav *.snm *.idx *.ilg *.ind _minted-* *.glo *.gls *.dpth *-tikztemp-*.pdf fig/*-converted-to.*
+FILE_CLEAN= *.executionerror *.diff *.log *.aux *.auxlock *.out *.blg *.bbl *.toc *.xml *.bcf *.synctex.gz *~ *.nav *.snm *.idx *.ilg *.ind _minted-* *.glo *.gls *.dpth *-tikztemp-*.pdf fig/*-converted-to.*
 ifndef DEBUG
 	DEBUG=> /dev/null
 endif
@@ -20,7 +21,7 @@ endif
 .NOTPARALLEL := test
 
 .PHONY: all test clean distclean $(TEX_ENGINES)
-.SECONDARY: $(foreach engine,$(TEX_ENGINES),$(PDFLATEX_TEST_FILES:.tex=_pdflatex-$(SUFFIX).xml) $(XETEX_TEST_FILES:.tex=_pdflatex-$(SUFFIX).xml) $(LUATEX_TEST_FILES:.tex=_pdflatex-$(SUFFIX).xml))
+.SECONDARY: $(foreach engine,$(TEX_ENGINES),$(PDFLATEX_TEST_FILES:.tex=_pdflatex-$(SUFFIX).xml) $(XETEX_TEST_FILES:.tex=_xelatex-$(SUFFIX).xml) $(LUATEX_TEST_FILES:.tex=_lualatex-$(SUFFIX).xml))
 
 all: test
 
@@ -36,30 +37,39 @@ clean:
 	rm -rf $(FILE_CLEAN)
 
 distclean: clean
-	rm -rf *.pdf *.xml *.diff *.md5 *.py *.err $(SUFFIX).sty
+	rm -rf *.pdf *.xml *.diff *.md5 *.py *.err *.executionerror $(SUFFIX).sty
 
 %_pdflatex-$(SUFFIX).xml : %.tex $(SUFFIX).sty
-	@pdflatex $(LATEXFLAGS) $< $(DEBUG)
-	@mv $(basename $<)-$(SUFFIX).xml $@
+	@pdflatex $(LATEXFLAGS) $< $(DEBUG)>/dev/null 2>&1 && mv $(basename $<)-$(SUFFIX).xml $@ || touch $(basename $<)-$(SUFFIX)_pdflatex.executionerror
 
 %_xelatex-$(SUFFIX).xml : %.tex $(SUFFIX).sty
-	@xelatex $(LATEXFLAGS) $< $(DEBUG)
-	@mv $(basename $<)-$(SUFFIX).xml $@
+	@xelatex $(LATEXFLAGS) $< $(DEBUG)>/dev/null 2>&1 && mv $(basename $<)-$(SUFFIX).xml $@ || touch $(basename $<)-$(SUFFIX)_xelatex.executionerror
 
 %_lualatex-$(SUFFIX).xml : %.tex $(SUFFIX).sty
-	@lualatex $(LATEXFLAGS) $< $(DEBUG)
-	@mv $(basename $<)-$(SUFFIX).xml $@
+	@lualatex $(LATEXFLAGS) $< $(DEBUG)>/dev/null 2>&1 && mv $(basename $<)-$(SUFFIX).xml $@ || touch $(basename $<)-$(SUFFIX)_lualatex.executionerror
 
 OK = "$$(tput setaf 0)$$(tput setab 2)[  OK  ]$$(tput sgr0)"
 KO = "$$(tput setaf 0)$$(tput setab 1)[FAILED]$$(tput sgr0)"
 $(PREFIX)_%_pdflatex.diff : latin1ref/$(PREFIX)_%-$(SUFFIX).ref $(PREFIX)_%_pdflatex-$(SUFFIX).xml
-	@$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (pdflatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (pdflatex)" | sed -e "s/_/ /g"
+	@if [ -e $(notdir $(basename $<)_pdflatex.executionerror) ]; then \
+		echo "$(KO) $* (pdflatex)(execution error)" | sed -e "s/_/ /g"; \
+	else \
+		$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (pdflatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (pdflatex)" | sed -e "s/_/ /g"; \
+	fi
 
 $(PREFIX)_%_xelatex.diff : utf8ref/$(PREFIX)_%-$(SUFFIX).ref $(PREFIX)_%_xelatex-$(SUFFIX).xml
-	@$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (xelatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (xelatex)" | sed -e "s/_/ /g"
+	@if [ -e $(notdir $(basename $<)_xelatex.executionerror) ]; then \
+		echo "$(KO) $* (xelatex)(execution error)" | sed -e "s/_/ /g"; \
+	else \
+		$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (xelatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (xelatex)" | sed -e "s/_/ /g"; \
+	fi
 	
 $(PREFIX)_%_lualatex.diff : utf8ref/$(PREFIX)_%-$(SUFFIX).ref $(PREFIX)_%_lualatex-$(SUFFIX).xml
-	@$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (lualatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (lualatex)" | sed -e "s/_/ /g"
+	@if [ -e $(notdir $(basename $<)_lualatex.executionerror) ]; then \
+		echo "$(KO) $* (lualatex)(execution error)" | sed -e "s/_/ /g"; \
+	else \
+		$(DIFFTOOL) $^ > $@ && echo "$(OK) $* (lualatex)"  | sed -e "s/_/ /g" || echo "$(KO) $* (lualatex)" | sed -e "s/_/ /g"; \
+	fi
 
 $(SUFFIX).sty: ../$(SUFFIX).sty
 	cp $< $@
